export const cities = [
  'A Coruña',
  'Alava',
  'Albacete',
  'Alicante',
  'Almería',
  'Asturias',
  'Avila',
  'Badajoz',
  'Barcelona',
  'Burgos',
  'Cáceres',
  'Cádiz',
  'Cantabria',
  'Castellón',
  'Ceuta',
  'Ciudad Real',
  'Córdoba',
  'Cuenca',
  'Formentera',
  'Girona',
  'Granada',
  'Guadalajara',
  'Guipuzcoa',
  'Huelva',
  'Huesca',
  'Ibiza',
  'Jaén',
  'La Rioja',
  'Las Palmas de Gran Canaria',
  'Gran Canaria',
  'Fuerteventura',
  'Lanzarote',
  'León',
  'Lleida',
  'Lugo',
  'Madrid',
  'Málaga',
  'Mallorca',
  'Menorca',
  'Murcia',
  'Navarra',
  'Orense',
  'Palencia',
  'Pontevedra',
  'Salamanca',
  'Santa Cruz de Tenerife',
  'Tenerife',
  'La Gomera',
  'La Palma',
  'El Hierro',
  'Sevilla',
  'Soria',
  'Tarragona',
  'Teruel',
  'Toledo',
  'Valencia',
  'Valladolid',
  'Vizcaya',
  'Zamora',
  'Zaragoza',
];

export const roles = ['developer', 'designer', 'product'];
